### PR TITLE
Few changes in login page ui.

### PR DESCRIPTION
**Pull request by epselon007**
*added background image.

*changed "Welocome to IIT BHU's workshop App" to "Welcome to IIT BHU".

*changed the color of outline button

*shifted the guest icon button to bottom right.

### CODE REVIEW

**Comment by epselon007** [comment]
i had submit a pull request to make changes in login page ui.

**Review by dev-raj-1729 — CHANGES_REQUESTED** [review]
Replace deprecated OutlineButton with OutlinedButton
Replace 

```
OutlineButton(
              splashColor: Colors.grey,
              
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(40)),
              highlightElevation: 0,
              borderSide: BorderSide(color: Colors.purple)
                     .
                     .
```

part with 
```
OutlinedButton(
              style: outlineButtonStyle.copyWith(
                shape: MaterialStateProperty.all<OutlinedBorder>(
                  RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(40)),
                ),
                side: MaterialStateProperty.resolveWith<BorderSide>((states) {
                  if (states.contains(MaterialState.pressed))
                    return BorderSide(
                      color: Theme.of(context).colorScheme.primary,
                      width: 1,
                    );
                  return BorderSide(color: Colors.purple);
                }),
                elevation: MaterialStateProperty.resolveWith<double?>((states) {
                  if (states.contains(MaterialState.pressed)) return 0.0;
                  return null;
                }),
                overlayColor: MaterialStateProperty.resolveWith(
                  (states) {
                    if (states.contains(MaterialState.pressed))
                      return Colors.grey;
                    return null;
                  },
                ),
```
It should have the same appearance as before

**Comment by Vikhyath08** [comment]
Yes. Also, put the GUEST button as a `FloatingActionButton` instead of another element in the `ListView`.

**Comment by epselon007** [comment]
I had changed deprected OutlineButton to OutlinedButton

**Comment by epselon007** [comment]
i had chanded guest button to FAB button.

**Comment by Vikhyath08** [comment]
Yep. This PR looks good and works well.
A small piece of advice would be to not work on the main branch of your fork, but to create a separate branch for every PR, so that you can work on more than one issue at a time.
Regardless, good work @epselon007 .

**Pull request merged**
