### PR TITLE
Introduced new Home Screen

### PR DESCRIPTION
**Pull request by ItsAdityaKSingh**
**Co-authored by** : Drishti Bansal *(https://github.com/stuck-in-a-conundrum)* , Ayush Bharsakle *(https://github.com/bayush-9)* , Puranjay Khanijo *(https://github.com/puranjayK)*
**Changes made** - Introduced a new home page according to designated UI.
>The screen can be accessed from AppDrawer.

*Required events and noticeboard information can be fetched by backend once required API requirements are made.*

### CODE REVIEW

**Comment by Vikhyath08** [comment]
A few changes need to be made:

- [ ] In the ongoing events section, there is nothing to be done in the backend. This info is already present in the frontend and is being displayed in the current home screen. It is currently empty, so even your home page would be empty. So just display the past workshops/events here for now instead of ongoing events.
- [ ] On the top right of the screen, the profile picture of the user should be shown, like [this](https://github.com/IIT-BHU-InstiApp/IIT-BHU-app/blob/82f66d236870649597b6cef4ed3fd5d32090f08c/lib/pages/academics/academicsPage.dart#L85).
- [ ] Use a ListView instead of a Row in the Events class, and make sure it is updatable. Refer to [this](https://www.youtube.com/watch?v=IOyq-eTRhvo).
- [ ] Make sure the data is dynamic in both the ongoing events and in the Noticeboard. Refer to existing code for this.

**Comment by ItsAdityaKSingh** [comment]
### Few required changes done

  

1. ***Images of workshops and events to be added instead of clubs***
2. ***Noticeboard yet not updated***

**Comment by stuck-in-a-conundrum** [comment]
### Changes for Noticeboard done

**Comment by Vikhyath08** [comment]
A few changes to be made:

- [ ] While implementing the database logic for NoticeSummary, it would be great if you would simultaneously implement the logic for NoticeDetail as well.
- [ ] Implement the search operation.
- [ ] Add an _onPopHome() function like [this](https://github.com/IIT-BHU-InstiApp/IIT-BHU-app/blob/3629e567db1e5a13db041d139fe8b5c25ec6cd84/lib/pages/Home/homePage.dart#L61).

**Comment by ItsAdityaKSingh** [comment]
> A few changes to be made:
> 
> * [ ]  While implementing the database logic for NoticeSummary, it would be great if you would simultaneously implement the logic for NoticeDetail as well.
> * [ ]  Implement the search operation.
> * [ ]  Add an _onPopHome() function like [this](https://github.com/IIT-BHU-InstiApp/IIT-BHU-app/blob/3629e567db1e5a13db041d139fe8b5c25ec6cd84/lib/pages/Home/homePage.dart#L61).

NoiceDetail, as if a new page having more info about the particular notice that has been clicked?

**Comment by Vikhyath08** [comment]
> > A few changes to be made:
> > 
> > * [ ]   While implementing the database logic for NoticeSummary, it would be great if you would simultaneously implement the logic for NoticeDetail as well.
> > * [ ]   Implement the search operation.
> > * [ ]   Add an _onPopHome() function like [this](https://github.com/IIT-BHU-InstiApp/IIT-BHU-app/blob/3629e567db1e5a13db041d139fe8b5c25ec6cd84/lib/pages/Home/homePage.dart#L61).
> 
> NoiceDetail, as if a new page having more info about the particular notice that has been clicked?

I'm not talking about creating any new pages. What I'm saying is just like there's a database for NoticeDetail [here](https://github.com/IIT-BHU-InstiApp/IIT-BHU-app/pull/326/files#diff-f02c7a9c467a4fd2397b1dce2a3587ad4fa44b4797ba48c8e0a88d556f04e7b4R83), there should also be one [here](https://github.com/IIT-BHU-InstiApp/IIT-BHU-app/pull/326/files#diff-8fe9794002a718894470156c2927564883a52fde1ee951eae462704966f41e35R171), and other similar places where NoticeSummary has been implemented.

**Pull request merged**
