### PR TITLE
UI tweaks in About Page and NavBar

### PR DESCRIPTION
**Pull request by ARJUPTA**
UI tweaks in About Page and NavBar also added the functionality of opening of GitHub profile from about page.

### CODE REVIEW

**Comment by ARJUPTA** [comment]
@nishantkr18 , Please Take A Look

**Review by Vikhyath08 — APPROVED** [review]
LGTM @nishantkr18 . I think this can be merged.

**Comment by Vikhyath08** [comment]
@ARJUPTA Are you adding further commits or can I merge this?

**Comment by ARJUPTA** [comment]
> @ARJUPTA Are you adding further commits or can I merge this?

There is one more commit to perform. Will be doing it today

**Review by Vikhyath08 — APPROVED** [review]
LGTM!

**Pull request merged**
