### PR TITLE
code cleanind

### PR DESCRIPTION
**Pull request by sanyud24**
created six model classes of 6 tables functions included to map and frommap

### CODE REVIEW

**Comment by mohit-mangal** [comment]
@sanyud24  please run these 3 commands first - 
git rm -r --cached .
git add .
git commit -m "reset gitignore to prevent pubspec.lock"

**Comment by sanyud24** [comment]
it said 
nothing to commit , working tree is clean ..nothing got added

**Comment by mohit-mangal** [comment]
@sanyud24 I don't know why this didn't work for you. check these screenshots for reference. 
Screenshot (54)
Screenshot (55)

**Comment by mohit-mangal** [comment]
@sanyud24 please Capitalize first letter of class names.  For now I am correcting that. And always format the code before commit. 
Please ping me on telegram, we need to discuss your code.

**Pull request closed without merging**
