### PR TITLE
Fixed issue #181 : Automatically updating account screen

### PR DESCRIPTION
**Pull request by Captain-Kirk83**

### CODE REVIEW

**Comment by mohit-mangal** [comment]
This is not working as expected !!! @Captain-Kirk83 

ezgif com-gif-maker

**Comment by Captain-Kirk83** [comment]
But it is working for me

**Comment by Captain-Kirk83** [comment]
It is working for me

**Comment by mohit-mangal** [comment]
@Captain-Kirk83  this is working with the back button provided at top left, but if we press hardware back button, it doesn't work. Please check that out.

**Review by mohit-mangal — CHANGES_REQUESTED** [review]
delete android/.project and .settings file, put them in gitignore

**Comment by Captain-Kirk83** [comment]
@mohit-mangal plz review it once again

**Review by mohit-mangal — APPROVED** [review]

**Comment by mohit-mangal** [comment]
@Captain-Kirk83 
You can see that after adding those files in .gitignore , those files can still be observed in file changes. You need to do one more commit, these are the instructions - 

git rm -r --cached .
git add .
git commit -m "removed .project and .settings from android/"

run these three commands

**Pull request merged**
