### PR TITLE
Fixed the RenderFlex issue in contacts

### LINKED ISSUE #185: Long name in contacts throws a RenderFlex issue
A long name in the contacts is not rendered properly.

### PR DESCRIPTION
**Pull request by Vikhyath08**
Closes #185

### CODE REVIEW

**Comment by nishantkr18** [comment]
image
I dont think its working the way it should :thinking:

**Comment by nishantkr18** [comment]
Hey, could u limit the names to two words only? for PORs as well as contacts of workshops?

**Comment by Vikhyath08** [comment]
I've made it two lines instead of two words. This may have the side effect of displaying 4/5 Year in some cases, but showing only first 2 words is, I believe, computationally unnecessary.

**Comment by nishantkr18** [comment]
> I've made it two lines instead of two words. This may have the side effect of displaying 4/5 Year in some cases, but showing only first 2 words is, I believe, computationally unnecessary.

Grt, but make the changes in workshop contacts as well.

**Comment by nishantkr18** [comment]
Nice!

**Pull request merged**
